# Generated by Django 3.1.3 on 2020-12-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='cathegory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='decription',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='date',
        ),
        migrations.AddField(
            model_name='item',
            name='url_link',
            field=models.CharField(default='none', max_length=1024),
            preserve_default=False,
        ),
    ]
